---
# defaults file for roles/lets_encrypt
# domain_name: your-domain
# lets_encrypt_acme_email: certificate-reminders@your-domain
lets_encrypt_cert_country: EU
lets_encrypt_cert_organization: Custom website

lets_encrypt_site_dir: /var/www/html
lets_encrypt_acme_challenge_type: http-01
lets_encrypt_acme_challenge_dir: "{{ lets_encrypt_site_dir }}/.well-known/acme-challenge"
lets_encrypt_acme_dir: https://acme-v02.api.letsencrypt.org/directory
lets_encrypt_acme_version: 2
lets_encrypt_dir: /etc/letsencrypt
lets_encrypt_dirs:
  - "{{ lets_encrypt_dir }}/keys"
  - "{{ lets_encrypt_dir }}/csrs"
  - "{{ lets_encrypt_dir }}/accounts"
lets_encrypt_certs_dir: "{{ lets_encrypt_dir }}/live/{{ domain_name }}"
lets_encrypt_key_path: "{{ lets_encrypt_dir }}/keys/{{ domain_name }}.key"
lets_encrypt_csr_path: "{{ lets_encrypt_dir }}/csrs/{{ domain_name }}.csr"
lets_encrypt_account_key_path: "{{ lets_encrypt_dir }}/accounts/{{ domain_name }}.key"
lets_encrypt_tiny_acme_path: "/opt/tiny_acme.py"
lets_encrypt_tiny_acme_url: "https://raw.githubusercontent.com/diafygi/acme-tiny/master/acme_tiny.py"
