---
# tasks file for roles/selfsign_certificate
# Based on https://docs.ansible.com/ansible/latest/collections/community/crypto/docsite/guide_ownca.html
- name: Generate a ca certificate key
  community.crypto.openssl_privatekey:
    path: "{{ selfsign_certificate_ca_key }}"
    passphrase: "{{ selfsign_certificate_ca_passphrase }}"
    cipher: auto
    type: RSA
    size: 4096

- name: Generate a certificate key
  community.crypto.openssl_privatekey:
    path: "{{ selfsign_certificate_key }}"
    type: RSA
    size: 4096

- name: Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ selfsign_certificate_ca_key }}"
    common_name: VPN ROOT CA
    use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - Certificate Sign
      - CRL Sign
    key_usage_critical: true
  register: ca_csr

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ selfsign_certificate_ca_path }}"
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: "{{ selfsign_certificate_ca_key }}"
    privatekey_passphrase: "{{ selfsign_certificate_ca_passphrase }}"
    provider: selfsigned
    selfsigned_not_after: +3650d # valid for 10 years

- name: Create certificate signing request (CSR) for new certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ selfsign_certificate_key }}"
    common_name: "{{ selfsign_certificate_cn }}"
    subject_alt_name:
      - "DNS:{{ selfsign_certificate_san }}"
      - "IP:{{ selfsign_certificate_san }}"
    extended_key_usage:
      - TLS Web Server Authentication
      - 1.3.6.1.5.5.8.2.2
  register: csr

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    provider: ownca
    csr_content: "{{ csr.csr }}"
    path: "{{ selfsign_certificate_path }}"
    ownca_path: "{{ selfsign_certificate_ca_path }}"
    ownca_privatekey_path: "{{ selfsign_certificate_ca_key }}"
    ownca_privatekey_passphrase: "{{ selfsign_certificate_ca_passphrase }}"
    ownca_create_subject_key_identifier: never_create
    ownca_not_after: +3650d # valid for 10 years
