---
# defaults file for ssh_configure
ssh_ignore_rhosts: true
ssh_password_authentication: false
ssh_permit_root_login: false
ssh_disable_forwarding: true
ssh_port: "{{ 20000 | random(start=10000, seed=inventory_hostname) }}" # Changes the default value for another persistent port
ssh_fwd_bantime: 86400 # Secs 86400 - 1 day, 604800 - 7 days
ssh_fwd_ip_list_tot: 102400 # Ip addr ist size
ssh_save_host: true # Saves this host in the local ssh conf
