---
# handlers file for roles/lets_encrypt
- name: Remove defaults nginx
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/conf.d/default

- name: Letsencrypt nginx reload
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
    enabled: true
