---
- name: "Create user {{ uusername }} with sudo = {{ usudo }} with pass"
  ansible.builtin.user:
    name: "{{ uusername }}"
    password: "{{ upassword | password_hash('sha512') }}"
    groups: sudo
    append: "{{ usudo }}"
    createhome: "{{ upublic_key is defined }}"
    shell: /bin/bash
  when: upassword is defined

- name: "Create user {{ uusername }} with sudo = {{ usudo }} without pass"
  ansible.builtin.user:
    name: "{{ uusername }}"
    groups: sudo
    append: "{{ usudo }}"
    createhome: true
    shell: /bin/bash
  when: upassword is not defined

- name: Create dir
  ansible.builtin.file:
    path: /home/{{ uusername }}/.ssh
    state: directory
    mode: "0700"
    owner: "{{ uusername }}"
    group: "{{ uusername }}"
  when: upublic_key is defined

- name: Set key from file
  ansible.posix.authorized_key:
    user: "{{ uusername }}"
    state: present
    key: "{{ lookup('file', upublic_key) }}"
  when: upublic_key is defined

- name: Set sudoers nopasswd
  community.general.sudoers:
    name: "{{ uusername }}-user"
    user: "{{ uusername }}"
    commands: ALL
    nopassword: "{{ unopasswd }}"
  when: usudo
