---
- name: "Create user {{ user_create_name }} with sudo = {{ user_create_sudo }} with pass"
  ansible.builtin.user:
    name: "{{ user_create_name }}"
    password: "{{ user_create_password | password_hash('sha512') }}"
    groups: sudo
    append: "{{ user_create_sudo }}"
    create_home: "{{ user_create_home }}"
    shell: "{{ user_create_shell }}"
    system: "{{ user_create_system }}"
  when: user_create_password is defined

- name: "Create user {{ user_create_name }} with sudo = {{ user_create_sudo }} without pass"
  ansible.builtin.user:
    name: "{{ user_create_name }}"
    groups: sudo
    append: "{{ user_create_sudo }}"
    create_home: "{{ user_create_home }}"
    shell: "{{ user_create_shell }}"
    system: "{{ user_create_system }}"
  when: user_create_password is not defined

- name: Create dir
  ansible.builtin.file:
    path: /home/{{ user_create_name }}/.ssh
    state: directory
    mode: '0700'
    owner: "{{ user_create_name }}"
    group: "{{ user_create_name }}"
  when: user_create_public_key

- name: Set key from file
  ansible.posix.authorized_key:
    user: "{{ user_create_name }}"
    state: present
    key: "{{ lookup('file', user_create_public_key) }}"
  when: user_create_public_key

- name: Set sudoers nopasswd
  community.general.sudoers:
    name: "{{ user_create_name }}-user"
    user: "{{ user_create_name }}"
    commands: ALL
    nopassword: "{{ user_create_sudo_nopasswd }}"
  when: user_create_sudo
