---
- name: Update file /etc/ufw/before.rules
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: '\*filter'
    block: "{{ lookup('ansible.builtin.template', 'templates/before.rules1.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK IPSEC 1"
  notify:
    - UFW disable
    - UFW enable

- name: Update file /etc/ufw/before.rules next
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: ':ufw-not-local - \[0:0\]'
    block: "{{ lookup('ansible.builtin.template', 'templates/before.rules2.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK IPSEC 2"
  notify:
    - UFW disable
    - UFW enable

- name: Update file /etc/ufw/sysctl.conf
  ansible.builtin.blockinfile:
    path: /etc/ufw/sysctl.conf
    block: "{{ lookup('ansible.builtin.template', 'templates/sysctl.conf.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK IPSEC"
  notify:
    - UFW disable
    - UFW enable

- name: Ufw allow ports
  community.general.ufw:
    rule: allow
    port: 500,4500
    proto: udp
    comment: IPSec ports
