---
- name: Check ssh service status
  ansible.builtin.systemd:
    name: ssh
    enabled: true
  register: ssh_status
  ignore_errors: true

- name: Add SSH config with key auto-added to agent
  connection: local
  become: false
  community.general.ssh_config:
    ssh_config_file: "~/.ssh/config"
    remote_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    host: "{{ ansible_host }}"
    port: "{{ ssh_port }}"
    state: present

- name: Copy ssh settings .conf
  ansible.builtin.template:
    src: external_ssh.conf.j2
    dest: /etc/ssh/sshd_config.d/10-external-ssh.conf
    mode: "0600"
    owner: root
    group: root
  notify:
    - Restart ssh

- name: SSH UFW configuration
  ansible.builtin.import_tasks: ufw.yml
  when: ssh_port != 22 and ansible_distribution | lower == 'ubuntu'
  tags:
    - firewall
