---
# handlers file for roles/socks5
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart danted
  ansible.builtin.systemd:
    name: danted
    state: restarted
