---
- name: Add docker repos
  block:
    - name: Dockerrepo | no apt key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: "0644"

    - name: Dockerrepo | apt source
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        filename: docker
        update_cache: false

- name: Apt update
  ansible.builtin.apt:
    update_cache: true

- name: Install docker
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
