---
- name: Basic Ubuntu configuring
  hosts: all
  become: true
  roles:
    - user_create
    - prometheus.prometheus.node_exporter
    - ssh
    - motd
  pre_tasks:
    - name: Firewall block
      tags:
        - firewall
      block:
        - name: Ufw allow app ssh
          community.general.ufw:
            rule: allow
            name: OpenSSH
            comment: OpenSSH allow app

        - name: Ufw enable and deny incoming
          community.general.ufw:
            state: enabled
            default: deny
            direction: incoming

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family | lower == 'debian'
      tags:
        - install_packages
  vars:
    user_create_name: ansible
    user_create_public_key: ~/.ssh/ansible.pub
