---
- name: Basic Ubuntu configuring
  hosts: all
  become: true
  roles:
    - user_create
    - prometheus.prometheus.node_exporter
    - ssh
    - motd
  pre_tasks:
    - name: Ufw allow app ssh
      community.general.ufw:
        rule: allow
        name: OpenSSH
        comment: OpenSSH allow app

    - name: Ufw allow node exporter
      community.general.ufw:
        rule: allow
        port: 9100
        src: 10.0.0.0/8

    - name: Ufw enable and deny incoming
      community.general.ufw:
        state: enabled
        default: deny
        direction: incoming
  vars:
    uusername: ansible
    upublic_key: ~/.ssh/ansible.pub
