---
- name: Basic Ubuntu configuring
  hosts: all
  become: true
  roles:
    - user_create
    - ssh
    - motd
    # - prometheus.prometheus.node_exporter
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts['os_family'] | lower == 'debian'
      tags:
        - install_packages

    - name: Firewall block
      when: ansible_facts['distribution'] | lower == 'ubuntu'
      tags:
        - firewall
      block:
        - name: Install Ufw
          ansible.builtin.apt:
            name:
              - ufw
            state: present

        - name: Ufw enable and deny incoming
          community.general.ufw:
            state: enabled
            default: deny
            direction: incoming

        - name: Comment allow ping rule
          ansible.builtin.replace:
            path: /etc/ufw/before.rules
            regexp: "^-A ufw-before-input -p icmp --icmp-type echo-request -j ACCEPT"
            replace: "# -A ufw-before-input -p icmp --icmp-type echo-request -j ACCEPT"
  vars:
    user_create_name: ansible
    user_create_public_key: ~/.ssh/ansible.pub
