---
- name: Create ansible user and add key
  hosts: all
  become: true
  roles:
    - user_create
  vars:
    user_create_name: ansible
    user_create_public_key: ~/.ssh/ansible.pub
    user_create_sudo: true
