---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
  notify:
    - Remove defaults nginx
  tags:
    - install_packages

- name: Open ufw port
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
    comment: "Open let`s encrypt checking port"
  tags:
    - firewall
