---
# tasks file for roles/lets_encrypt
# based on https://www.digitalocean.com/community/tutorials/how-to-acquire-a-let-s-encrypt-certificate-using-ansible-on-ubuntu-18-04
- name: Create required directories in /etc/letsencrypt
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0600'
  with_items:
    - "{{ lets_encrypt_dir }}"
    - "{{ lets_encrypt_dirs }}"
    - "{{ lets_encrypt_certs_dir }}"

- name: Generate a Let's Encrypt account key
  community.crypto.openssl_privatekey:
    path: "{{ lets_encrypt_account_key_path }}"
    size: 4096

- name: Generate Let's Encrypt private key
  community.crypto.openssl_privatekey:
    path: "{{ lets_encrypt_key_path }}"
    size: 4096

- name: Generate Let's Encrypt CSR
  community.crypto.openssl_csr:
    path: "{{ lets_encrypt_csr_path }}"
    privatekey_path: "{{ lets_encrypt_key_path }}"
    country_name: "{{ lets_encrypt_cert_country }}"
    organization_name: "{{ lets_encrypt_cert_organization }}"
    email_address: "{{ lets_encrypt_acme_email }}"
    common_name: "{{ domain_name }}"

- name: Import OS specific tasks
  ansible.builtin.import_tasks: 'http.yml'
  when: lets_encrypt_acme_challenge_type == 'http-01'

- name: Install tiny_acme
  ansible.builtin.get_url:
    url: "{{ lets_encrypt_tiny_acme_url }}"
    dest: "{{ lets_encrypt_tiny_acme_path }}"
    mode: '0500'
